server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tasks_db
    username: postgres
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/task-manager-realm

services:
  user-service:
    url: http://localhost:8084/
  project-service:
    url: http://localhost:8083/