server:
  port: 8082
  jetty:
    max-http-response-header-size: 65536

spring:
  cloud:
    gateway:
      routes:
        - id: manager-application
          uri: http://localhost:8080/
          predicates:
            - Path=/**
          order: 5

        - id: tasks-service
          uri: http://localhost:8081/task-manager-api/tasks
          predicates:
            - Path=/task-manager-api/tasks/**
          order: 1

        - id: user-service
          uri: http://localhost:8084/task-manager-api/users
          predicates:
            - Path=/task-manager-api/users/**
          order: 2

        - id: projects-service
          uri: http://localhost:8081/task-manager-api/projects
          predicates:
            - Path=/task-manager-api/projects/**
          order: 3


      globalcors:
        cors-configurations:
          '[/**]': #api, доступ к которым будет открыт
            allowed-origins: "http://localhost:8080" # Разрешенные источники
            allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH # Разрешенные методы
            allowed-headers: "*" # Разрешенные заголовки
            allow-credentials: true # Разрешить передачу куки и заголовков авторизации
