server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/projects_db
    username: postgres
    password: admin


services:
  user-service:
    url: http://localhost:8084/
