server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/projects_db
    username: postgres
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/task-manager-realm


services:
  user-service:
    url: http://localhost:8084/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG #