spring:
  data:
    mongodb:
      uri: mongodb://alexgls:AS04SERa1@localhost:27017/task_notes?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/task-manager-realm

server:
  port: 8085

services:
  users:
    uri: http://localhost:8084/
